#!/bin/bash

# 환경변수 github url가 설정되어 있는지 확인
# 설정되지 않은 경우 에러 종료 (exit 1 = 에러나서 종료됨)
if [ -z $GITHUB_URL ]; then 
	exit 1
fi

# 처음에는 git clone을 통해서 컨텐츠를 가져옴
git clone $GITHUB_URL /data

#이후에는 60초마다 github에서 컨텐츠를 가져옴
cd /data
while true
do
	date
	sleep 60
	git pull
done